name: cd

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Yarn
        run: npm install -g yarn
      - name: Install pm2
        run: npm install -g pm2 
      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/app/HiSpace-BackEnd
            git pull origin master 
            git status
            ls -la
            npm install -g yarn
            npm install -g pm2 
            yarn install
            pm2 reload hispace
            pm2 restart hispace